# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('username', models.CharField(default='login', max_length=255)),
                ('password', models.CharField(default='12345', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(max_length=30, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('picture', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='office',
            field=models.ManyToManyField(related_name='members', to='rip_app.OfficesModel'),
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
