# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesmodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='officesmodel',
            name='named',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='officesmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
