# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0004_auto_20170117_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='test/', verbose_name=''),
        ),
    ]
