# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0005_auto_20170117_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersmodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='membersmodel',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='membersmodel',
            name='username',
        ),
    ]
