# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0008_auto_20170118_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='f_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='l_name',
            field=models.CharField(max_length=100, null=True, verbose_name='L_name'),
        ),
        migrations.AlterField(
            model_name='membersmodel',
            name='position',
            field=models.CharField(default='------', max_length=255, verbose_name='Position'),
        ),
    ]
